---
- hosts: 172.31.37.168
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: i want to copy file from ansible master to nodes
    copy:
      src: mystatic
      dest: /home/ubuntu/mystaticfile

  - name: I want to intall webserver
    apt:
      name: apache2
      state: present

  - name: copy dynamic file into node side
    template:
      src: myindexfile.j2
      dest: /var/www/html/index.html
    notify: restartwebserver

  - name: download remote file
    get_url:
      url: https://images.pexels.com/photos/60597/dahlia-red-blossom-bloom-60597.jpeg?cs=srgb&dl=pexels-pixabay-60597.jpg&fm=jpg
      dest: /home/ubuntu/pexels-pixabay-60597.jpg
      force_basic_auth: yes
  
  handlers:
  - name: restartwebserver
    service:
      name: apache2
      state: restarted
