---
- hosts: 172.31.37.168
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: i want to copy file from ansible master to nodes
    copy:
      src: mystatic
      dest: /home/ubuntu/mystaticfile

  - name: I want to intall webserver
    apt:
      name: apache2
      state: present

  - name: copy dynamic file into node side
    tamplate:
      src: myindexfile.j2
      dest: /var/www/html/index.html
