---
- hosts: all
  become: yes
  tasks:
  - name: I want to install webserver
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"

  - name: I want to start webserver
    service:
      name: apache2
      state: started
    when: ansible_os_family =="Debian"

  - name: I want to install webserver on Redhat
    yum:
      name: httpd
      state: present
    when: ansible_os_family =="RedHat"

  - name: I want to start webserver on Redhat
    service:
      name: httpd
      state: restarted
    when: ansible_os_family =="RedHat"