---
- hosts: mywebservers
  become: yes
  tasks:
  - name: I want to install webserver
    apt:
      name: "{{mywebpackageonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: I want to start webserver
    service:
      name: "{{mywebpackageonubuntu}}"
      state: started
    when: ansible_os_family =="Debian"

  - name: I want to install webserver on Redhat
    yum:
      name: "{{mywebpackageonredhat}}"
      state: present
    when: ansible_os_family =="RedHat"

  - name: I want to start webserver on Redhat
    service:
      name: "{{mywebpackageonredhat}}"
      state: started
    when: ansible_os_family =="RedHat"